### ISSUE TITLE
Exit after all processes being handled?

### ISSUE THREAD

**Issue by dontub** [bendikro/supervisord-dependent-startup#3]
Is there a reason for not exiting the listener after all processes have been handled? This could be done by changing the while condition in `_listen()` from `1` to `not self.startup_done`.

**Comment by bendikro** [comment]
I don't remember if I considered changing that, or if I tested it, so I guess I just kept the eternal loop from the [original project code ](https://github.com/jasoncorbett/ordered-startup-supervisord/blob/54e32080e673f1548c5d97ed483805d63754656a/ordered_startup_supervisord.py#L142)

If it works to exit after startup it can be changed. Is there a specific reason you want it to exit?

**Comment by dontub** [comment]
I don't see a reason to keep a process running that does nothing, even though the waste of resources is minimal in this case.

**Comment by bendikro** [comment]
Fixed in [58db05](https://github.com/bendikro/supervisord-dependent-startup/commit/58db0566204902906012f5bc23a8c28bc26ce1d8)
