### ISSUE TITLE
Readme.md doesn't specify [unix_http_server] is also required

### ISSUE THREAD

**Issue by neale-bpm** [bendikro/supervisord-dependent-startup#6]
To shortcut the thread in #1, if someone is modifying their existing supervisord.conf, then it's easy to miss that unix_http_server is also required.

Could you add this to the section in the Readme.md

```
[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; socket file mode (default 0700)
```

Thanks.

**Comment by bendikro** [comment]
Hi

The `unix_http_server` section is in the [example.md](https://github.com/bendikro/supervisord-dependent-startup/blob/master/example.md)? But there is no line with `chmod=0700`, is that necessary?

**Comment by neale-bpm** [comment]
Sorry.  My confusion. It was the docs in README.md that omitted it.  I think both of us on #1 hit the same issue, in adding to an existing .conf that didn't have unix_http_server.

I'll edit to ref README.md

**Comment by bendikro** [comment]
@neale-bpm 
I see. The example in the readme is not supposed to show a complete and working `supervisor.conf`, but I'll push an update with a working example.

**Comment by neale-bpm** [comment]
Looks good.  
Many thanks
